"""Create character and vehicles classes

Revision ID: 977eeef2651a
Revises: 6441a7aab070
Create Date: 2025-12-27 20:41:24.628660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977eeef2651a'
down_revision = '6441a7aab070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('birth_year', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=100), nullable=False),
    sa.Column('eye_color', sa.String(length=100), nullable=False),
    sa.Column('hair_color', sa.String(length=100), nullable=False),
    sa.Column('skin_color', sa.String(length=100), nullable=False),
    sa.Column('height', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vehicle_class', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('cost_in_credits', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=False),
    sa.Column('crew', sa.String(length=200), nullable=False),
    sa.Column('max_speed', sa.String(length=200), nullable=False),
    sa.Column('cargo_capacity', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('characters')
    # ### end Alembic commands ###
